const Image = {
  banner: '/image/banner.jpg',
  banner1: '/image/banner1.jpg',
  banner2: '/image/banner2.jpg',
  banner3: '/image/banner3.jpg',
  banner4: '/image/banner4.jpg',
  banner5: '/image/banner5.jpg',
  categorybanner1: '/image/categorybanner1.jpg',
  categorybanner2: '/image/categorybanner2.jpg',
  categorybanner3: '/image/categorybanner3.jpg',
  collection: '/image/collection.jpg',
  home_collection_banner: '/image/home_collection_banner.jpg',
  lookbooks_1: '/image/lookbooks_1.jpg',
  lookbooks_2: '/image/lookbooks_2.jpg',
  lookbooks_3: '/image/lookbooks_3.jpg',
  pro_featured: '/image/pro_featured.jpg',
  home_groupbanner_banner1: '/image/home_groupbanner_banner1.jpg',
  home_groupbanner_banner2: '/image/home_groupbanner_banner2.jpg',
  userprofile: '/image/userprofile.png',
  product_under_banner: '/image/product_under_banner.jpg',
  product_1: '/image/product_under1.1.jpg',
  product_1_1: '/image/product_under1.jpg',
  Carouselendpage1: '/image/Carouselendpage1.jpg',
  Carouselendpage2: '/image/Carouselendpage2.jpg',
  Carouselendpage3: '/image/Carouselendpage3.jpg',
  Carouselendpage4: '/image/Carouselendpage4.jpg',
  Carouselendpage5: '/image/Carouselendpage5.jpg',
  Carouselendpage6: '/image/Carouselendpage6.jpg',
  sizegiay: '/image/bangsizegiay.png',
  logoPay: '/image/logoPay.png',
  logoMomo: '/image/logoMomo.png',
  avatarClone: '/image/default-avatar.png',
};
export default Image;
